import type { Metadata } from 'next';
import './globals.css';
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme
          accentColor="indigo"
          panelBackground="translucent"
          radius="medium"
          scaling="100%"
          appearance="dark"
        >
          {children}
        </Theme>
      </body>
    </html>
  );
}
